; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27031.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Rafa³\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
